---
- name: Get list of dpdk ports
  include_tasks: ovs-dpdk-ports.yml

- debug:
    var: ovs_dpdk_ports

- name: Collect data
  include_tasks: datacollection.yml

- name: validate data of ovs_dpdk_ports
  vars:
    interface: "{{ port }}"
  include_tasks: validate.yml
  loop: "{{ ovs_dpdk_ports }}"
  loop_control:
    loop_var: port

